---
    name: "Release"
    
    on:
      push:
        branches:
          - main
    
    jobs:
        release:
            name: Release with new version
            runs-on: [ 'ubuntu-latest' ]
            timeout-minutes: 5
            permissions:
                id-token: write
                contents: read          
            steps:
                - uses: actions/checkout@v4

                - uses: actions-ecosystem/action-get-latest-tag@v1
                  id: get-latest-tag
                  with:
                    github_token: ${{ github.token }}
                
                - name: New release tag
                  id: newtag
                  uses: ./

                - uses: actions-ecosystem/action-bump-semver@v1
                  id: bump-semver
                  with:
                    current_version: ${{ steps.get-latest-tag.outputs.tag }}

                - uses: actions-ecosystem/action-push-tag@v1
                  with:
                    tag: ${{ steps.bump-semver.outputs.new_version }}
                    github_token: ${{ github.token }}
          